const PORT = 3003
const NODE_ENV = process.env.NODE_ENV
const MONGODB_CONNECT_STRING = NODE_ENV === 'test' ? process.env.MONGODB_TEST_CONNECT_STRING : process.env.MONGODB_CONNECT_STRING
const MIN_RAW_PASSWORD_LENGTH = 3
const MIN_USERNAME_LENGTH = 3

module.exports = { 
    PORT, 
    MONGODB_CONNECT_STRING, 
    MIN_RAW_PASSWORD_LENGTH,
    MIN_USERNAME_LENGTH 
}